create type parcel_status as enum ('completed', 'scheduled', 'in_progress', 'unassigned');

alter type parcel_status owner to postgres;

create type transit_status as enum ('completed', 'scheduled', 'in_progress');

alter type transit_status owner to postgres;

create table locations
(
    id   integer generated by default as identity
        primary key,
    city varchar(255) not null
        unique
);

alter table locations
    owner to postgres;

create table transits
(
    id                integer generated by default as identity
        primary key,
    start_location    integer                                            not null
        references locations,
    end_location      integer                                            not null
        references locations,
    max_load_kg       numeric(10, 2)                                     not null,
    width_m           numeric(6, 2)                                      not null,
    height_m          numeric(6, 2)                                      not null,
    depth_m           numeric(6, 2)                                      not null,
    current_load_kg   numeric(10, 2) default 0                           not null,
    status            transit_status default 'scheduled'::transit_status not null,
    created_at        timestamp      default now()                       not null,
    updated_at        timestamp      default now()                       not null,
    departure_date    timestamp                                          not null,
    arrival_date      timestamp                                          not null,
    current_volume_m3 numeric(6, 2)  default 0.0,
    constraint transits_check
        check (current_load_kg <= max_load_kg)
);

alter table transits
    owner to postgres;

create table parcels
(
    id             integer generated by default as identity
        primary key,
    start_location integer                                           not null
        references locations,
    end_location   integer                                           not null
        references locations,
    weight_kg      numeric(10, 2)                                    not null,
    width_m        numeric(6, 2)                                     not null,
    height_m       numeric(6, 2)                                     not null,
    depth_m        numeric(6, 2)                                     not null,
    status         parcel_status default 'unassigned'::parcel_status not null,
    transit_id     integer
                                                                     references transits
                                                                         on delete set null,
    created_at     timestamp     default now()                       not null,
    updated_at     timestamp     default now()                       not null
);

alter table parcels
    owner to postgres;

create function update_timestamp() returns trigger
    language plpgsql
as
$$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

alter function update_timestamp() owner to postgres;

create trigger update_transits_timestamp
    before update
    on transits
    for each row
execute procedure update_timestamp();

create trigger update_parcels_timestamp
    before update
    on parcels
    for each row
execute procedure update_timestamp();

